build-and-test-with-drm:
  image: alpine:3.19
  tags:
    - saas-linux-small-amd64
  script:
    - apk -q add git bash build-base meson linux-headers inih-dev libinput-dev libxkbcommon-dev libdrm-dev scdoc
    - git submodule init
    - git submodule update
    - ./test/test-with-drm.sh

build-and-test-without-drm:
  image: alpine:3.19
  tags:
    - saas-linux-small-amd64
  script:
    - apk -q add git bash build-base meson linux-headers inih-dev libinput-dev libxkbcommon-dev scdoc
    - git submodule init
    - git submodule update
    - ./test/test-without-drm.sh

build-iskey:
  image: alpine:3.19
  tags:
    - saas-linux-small-amd64
  script:
    - apk -q add git bash build-base meson linux-headers libevdev-dev
    - cd iskey
    - meson setup _build
    - meson compile -C _build
