[general]
#animations=true
#backend=fbdev|drm
#timeout=0

[keyboard]
#autohide=true
#layout=us
#popovers=true
#haptic_feedback=true

[textarea]
#obscured=true
#bullet=•

[theme]
#default=breezy-light
#alternate=breezy-dark

[input]
#keyboard=true
#pointer=true
#touchscreen=true

[hardware keyboard]
#rules=
#model=
#layout=
#variant=
#options=

[quirks]
#fbdev_force_refresh=false
#terminal_prevent_graphics_mode=false
#terminal_allow_keyboard_input=false
